/// SEARCH
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_SEARCH_INPUT = "CHANGE_SEARCH_INPUT";
export const SUBMIT_SEARCH = "SUBMIT_SEARCH";

//REQUEST
export const GET_LIST_ALL_THAY_BOI_REQUEST = "GET_LIST_ALL_THAY_BOI_REQUEST";
export const GET_LIST_ALL_THAY_BOI_REQUEST_SUCCESS =
  "GET_LIST_ALL_THAY_BOI_REQUEST_SUCCESS";
export const GET_LIST_ALL_THAY_BOI_REQUEST_FAILURE =
  "GET_LIST_ALL_THAY_BOI_REQUEST_FAILURE";

//FortuneTellerDetail
export const GET_DETAIL_FORTUNETELLER_EVALUATE = 'GET_DETAIL_FORTUNETELLER_EVALUATE';
export const GET_DETAIL_FORTUNETELLER_EVALUATE_SUCCESS = 'GET_DETAIL_FORTUNETELLER_EVALUATE_SUCCESS';
export const GET_DETAIL_FORTUNETELLER_EVALUATE_FAILURE = 'GET_DETAIL_FORTUNETELLER_EVALUATE_FAILURE';
